name: deploy-book
on:
  push:
    branches:
      - main

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          conda install ipykernel
          python -m ipykernel install --user --name ai --display-name "ai"
      - name: Install theme
        run: |
          git clone https://github.com/xinetzone/xin-css.git ./_static/xin-css
          git clone https://github.com/xinetzone/w3css.git ./_static/w3css

      # Build the book
      - name: Build the book
        run: |
          jupyter-book build .

      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
